# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: felrock
description: ""

baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

fs_github: felrock

base_font_family: "JetBrains Mono"

brand-color: "#28b16d"
text-color: "#3A4F66"

